server:
  port: 8085


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-curso-service
          uri: lb://ms-curso-serivce
          predicates:
            - Path=/alumno/**
