server:
  port: 8085


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-alumno-service
          uri: lb://ms-alumno-service
          predicates:
            - Path=/alumno/**, /grado/**
        - id: ms-profesores-service
          uri: lb://ms-profesores-service
          predicates:
            - Path=/profesores/**
        - id: ms-curso-service
          uri: lb://ms-curso-service
          predicates:
            - Path=/cursos/**
        - id: ms-userjwt-service
          uri: lb://ms-userjwt-service
          predicates:
            - Path=/auth/**
        - id: ms-matricula-service
          uri: lb://ms-matricula-service
          predicates:
            - Path=/matriculas/**